//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: stream.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

public protocol Proto_StreamServiceEventsCall: ClientCallBidirectionalStreaming {
  /// Do not call this directly, call `receive()` in the protocol extension below instead.
  func _receive(timeout: DispatchTime) throws -> Proto_Payload?
  /// Call this to wait for a result. Nonblocking.
  func receive(completion: @escaping (ResultOrRPCError<Proto_Payload?>) -> Void) throws

  /// Send a message to the stream. Nonblocking.
  func send(_ message: Proto_Request, completion: @escaping (Error?) -> Void) throws
  /// Do not call this directly, call `send()` in the protocol extension below instead.
  func _send(_ message: Proto_Request, timeout: DispatchTime) throws

  /// Call this to close the sending connection. Blocking.
  func closeSend() throws
  /// Call this to close the sending connection. Nonblocking.
  func closeSend(completion: (() -> Void)?) throws
}

public extension Proto_StreamServiceEventsCall {
  /// Call this to wait for a result. Blocking.
  func receive(timeout: DispatchTime = .distantFuture) throws -> Proto_Payload? { return try self._receive(timeout: timeout) }
}

public extension Proto_StreamServiceEventsCall {
  /// Send a message to the stream and wait for the send operation to finish. Blocking.
  func send(_ message: Proto_Request, timeout: DispatchTime = .distantFuture) throws { try self._send(message, timeout: timeout) }
}

fileprivate final class Proto_StreamServiceEventsCallBase: ClientCallBidirectionalStreamingBase<Proto_Request, Proto_Payload>, Proto_StreamServiceEventsCall {
  override class var method: String { return "/proto.StreamService/Events" }
}


/// Instantiate Proto_StreamServiceServiceClient, then call methods of this protocol to make API calls.
public protocol Proto_StreamServiceService: ServiceClient {
  /// Asynchronous. Bidirectional-streaming.
  /// Use methods on the returned object to stream messages,
  /// to wait for replies, and to close the connection.
  func events(completion: ((CallResult) -> Void)?) throws -> Proto_StreamServiceEventsCall

}

public final class Proto_StreamServiceServiceClient: ServiceClientBase, Proto_StreamServiceService {
  /// Asynchronous. Bidirectional-streaming.
  /// Use methods on the returned object to stream messages,
  /// to wait for replies, and to close the connection.
  public func events(completion: ((CallResult) -> Void)?) throws -> Proto_StreamServiceEventsCall {
    return try Proto_StreamServiceEventsCallBase(channel)
      .start(metadata: metadata, completion: completion)
  }

}

