source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
swift_version = '4.1'
use_frameworks!
inhibit_all_warnings!

def pods
  pod 'PlasmaSwift', :path => '../'
  pod 'SwiftGRPC', git: 'https://github.com/grpc/grpc-swift.git', tag: '0.5.0'
end

target 'PlasmaSwift-Demo' do
  pods
end

target 'PlasmaSwift-DemoTests' do
  pods
end
